permalink: /:year:month:day/:title
url: #dev-jg.github.io/
baseurl: /project

# variables
name: [BackEnd Engineer] Jung Goo Lee
description: [BackEnd Engineer] Jung Goo Lee 히스토리
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
